import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogPost from "@/components/BlogCard";
import AboutMe from "@/components/AboutMe";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Marquee from "@/components/Maquee";
import ShareButton from "@/components/ShareButton";
import Title from "@/components/Title";

const graphcms = new GraphQLClient(
  "https://api-sa-east-1.hygraph.com/v2/clg3s1ng31koi01t3deilhg2d/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      description
      tag
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Wagner Silva | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <Hero />
        <Marquee />

        <section className="container">
          <Title title="QUEM SOU" subtitle="Apresentação" />
          <AboutMe />
        </section>

        <section>
          <Title title="BLOG" subtitle="Minhas publicações" />
          <div className={styles.dflex}>
            {posts.map((post) => (
              <BlogPost
                title={post.title}
                description={post.description}
                author={post.author}
                coverPhoto={post.coverPhoto}
                content={post.content}
                key={post.id}
                datePublished={post.datePublished}
                slug={post.slug}
                tag={post.tag}
              />
            ))}
          </div>
        </section>
      </main>

      <footer>
        <Footer />
        <ShareButton />
      </footer>
    </>
  );
}
